apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 182271742010.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "rootpassword"
    - name: MYSQL_DATABASE
      value: "employees"
    - name: MYSQL_USER
      value: "user"
    - name: MYSQL_PASSWORD
      value: "password"
  imagePullSecrets:
  - name: ecr-secret

