apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 182271742010.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:v2.0
    ports:
    - containerPort: 8080
    env:
    - name: DB_HOST
      value: "mysql-service.mysql-ns.svc.cluster.local"
    - name: DB_PORT
      value: "3306"
    - name: DB_USER
      value: "user"
    - name: DB_PASSWORD
      value: "password"
    - name: DB_NAME
      value: "employees"
  imagePullSecrets:
  - name: ecr-secret

